footer.footer
	.level
		.level-item
			ul
				/ FIXME: Add links.
				li
					a href="https://crystal-lang.org/"
						.heading 🖤\u{FE0E} Crystal
				li
					a href="https://kemalcr.com/"
						.heading 🖤\u{FE0E} Kemal
		.level-item
			span.title.is-4
				| © みい-ちゃん / Mii-chan Online
		.level-item
			ul
				li
					a href="https://git.karchnu.fr/JunkOS/libipc"
						.heading libipc 🖤\u{FE0E}
				li
					a href="https://github.com/FartingNicoNyanCats/frontd"
						.heading frontd 🖤\u{FE0E}

